### ISSUE TITLE
test

### ISSUE THREAD

**Issue by MasterLuke117** [ign-gg/Nukkit#29]
See below stuff,

```
network:
  version: 2
  renderer: networkd
  ethernets:
   id0:
      match:
        macaddress: 00:1e:67:bd:a0:c8
      addresses:
        - 66.181.42.53/27
        - 66.181.42.54/27
        - 66.181.42.55/27
        - 66.181.42.56/27
        - 66.181.42.57/27
      gateway4: 66.181.42.33
      nameservers:
        addresses:
          - 127.0.0.1
```
![trap2](https://user-images.githubusercontent.com/42286665/74420391-fc721680-4e10-11ea-956a-e14a8e165b94.jpg)
